export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const SORT_INGREDIENTS = "SORT_INGREDIENTS";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const RESET_INGREDIENT = "RESET_INGREDIENT";
